foreground            #e1e2e9
background            #111318
selection_foreground  #00315e
selection_background  #a6c8ff
url_color             #dabde2
cursor                #a6c8ff
cursor_text_color     #00315e

color0   #111318
color1   #ffb4ab
color2   #a6c8ff
color3   #dabde2
color4   #a6c8ff
color5   #dabde2
color6   #553f5d
color7   #e1e2e9

color8   #8d9199
color9   #ffb4ab
color10  #a6c8ff
color11  #dabde2
color12  #a6c8ff
color13  #dabde2
color14  #553f5d
color15  #e1e2e9

tab_bar_background              #111318
tab_bar_margin_color            #111318
active_tab_foreground           #00315e
active_tab_background           #a6c8ff
inactive_tab_foreground         #c3c6cf
inactive_tab_background         #111318
