-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("ALT + space")
hl.bind("ALT + space", hl.dsp.exec_cmd("dms ipc call spotlight-bar toggle"), { description = "dms ipc call spotlight-bar toggle" })
hl.unbind("End")
hl.bind("End", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "dms ipc call powermenu toggle" })
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "dms ipc call clipboard toggle" })
hl.unbind("CTRL + SHIFT + Tab")
hl.bind("CTRL + SHIFT + Tab", hl.dsp.window.move({ workspace = "e+1" }), { description = "move to workspace e+1 (non-silent)" })
hl.unbind("F1")
hl.bind("F1", hl.dsp.focus({ workspace = "1" }), { description = "focus workspace 1" })
hl.unbind("F2")
hl.bind("F2", hl.dsp.focus({ workspace = "2" }), { description = "focus workspace 2" })
hl.unbind("SUPER + ALT + Left")
hl.bind("SUPER + ALT + Left", hl.dsp.window.move({ workspace = "e-1" }), { description = "move to workspace e-1 (non-silent)" })
hl.unbind("SUPER + ALT + Right")
hl.bind("SUPER + ALT + Right", hl.dsp.window.move({ workspace = "e+1" }), { description = "move to workspace e+1 (non-silent)" })
hl.unbind("SUPER + SHIFT + 1")
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }), { description = "move to workspace 1 (non-silent)" })
hl.unbind("ALT + 1")
hl.bind("ALT + 1", hl.dsp.exec_cmd("/usr/local/bin/niflveil minimize"), { description = "/usr/local/bin/niflveil minimize" })
hl.unbind("ALT + 2")
hl.bind("ALT + 2", hl.dsp.exec_cmd("/usr/local/bin/niflveil restore-last"), { description = "/usr/local/bin/niflveil restore-last" })
hl.unbind("ALT + D")
hl.bind("ALT + D", hl.dsp.exec_cmd("skwd-wall-v2"), { description = "skwd-wall-v2" })
hl.unbind("ALT + F3")
hl.bind("ALT + F3", hl.dsp.exec_cmd("skwd-wall-v2"), { description = "skwd-wall-v2" })
hl.unbind("ALT + Q")
hl.bind("ALT + Q", hl.dsp.exec_cmd("kitty"), { description = "kitty" })
hl.unbind("ALT + S")
hl.bind("ALT + S", hl.dsp.exec_cmd("sh -c \"rofi -show drun\""))
hl.unbind("ALT + X")
hl.bind("ALT + X", hl.dsp.exec_cmd("bash ~/.config/hypr/powermenu.sh"), { description = "bash ~/.config/hypr/powermenu.sh" })
hl.unbind("0")
hl.unbind("ALT + Delete")
hl.unbind("ALT + Down")
hl.unbind("ALT + Escape")
hl.bind("ALT + Escape", hl.dsp.window.close(), { description = "Close window" })
hl.unbind("ALT + F")
hl.bind("ALT + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Toggle maximization" })
hl.unbind("ALT + K")
hl.unbind("ALT + M")
hl.unbind("ALT + R")
hl.bind("ALT + R", hl.dsp.window.float({ action = "toggle" }), { description = "Float/unfloat window" })
hl.unbind("ALT + Up")
hl.unbind("Equal")
hl.unbind("Escape")
hl.unbind("Home")
hl.unbind("Page_Down")
hl.unbind("Page_Up")
hl.unbind("SUPER + 1")
hl.unbind("SUPER + 2")
hl.unbind("SUPER + CTRL + U")
hl.unbind("SUPER + CTRL + down")
hl.unbind("SUPER + CTRL + up")
hl.unbind("SUPER + F")
hl.unbind("SUPER + Q")
hl.unbind("SUPER + SHIFT + T")
hl.unbind("SUPER + T")
hl.unbind("SUPER + X")
hl.unbind("SUPER + Period")
hl.bind("SUPER + Period", hl.dsp.exec_cmd("dms ipc call emojiPicker open"), { description = "Emoji Picker" })
