-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "pixelfun2-monochrome")
hl.env("XCURSOR_THEME", "pixelfun2-monochrome")
hl.env("HYPRCURSOR_SIZE", "22")
hl.env("XCURSOR_SIZE", "22")
